Demo_projects/Models/Billing.cs
using Microsoft.VisualBasic;
using System.ComponentModel.DataAnnotations;

namespace Demo_projects.Models
{
    public class Billing
    {
        [Key]
        public int BillNo { get; set; }
        public int CustomertNo { get; set;}
        public DateTime Date { get; set;}
        public string Amount { get; set;}
        public bool IsPaid { get; set;}
    }
}

Demo_projects/Models/ErrorViewModel.cs
namespace Demo_projects.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Demo_projects/Controllers/BillingController.cs
using Demo_projects.AppContectDb;
using Demo_projects.Models;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel;

namespace Demo_projects.Controllers
{
    public class BillingController : Controller
    {

        public IActionResult Index()
        {
            List<Billing> billingList = new List<Billing>();
            using (var dbContext = new AppDbContext())
            {
                dbContext.Database.EnsureCreated();

                billingList = dbContext.Billings.ToList();

            }
            return View(model: billingList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Billing billing)
        {
            using (var dbContext = new AppDbContext())
            {
                dbContext.Database.EnsureCreated();

                dbContext.Billings.Add(billing);
                dbContext.SaveChanges();
                return RedirectToAction("Index");

            }
            return View();
        }
        public IActionResult Edit(int Id)
        {
            Billing billing = new Billing();
            using (var dbContext = new AppDbContext())
            {
                dbContext.Database.EnsureCreated();

                billing = dbContext.Billings.Where(x => x.BillNo == Id).FirstOrDefault();

            }

            return View(billing);
        }
        [HttpPost]
        public IActionResult Edit(Billing billing)
        {
            using (var dbContext = new AppDbContext())
            {
                dbContext.Database.EnsureCreated();

                Billing billingGet = dbContext.Billings.Where(x => x.BillNo == billing.BillNo).FirstOrDefault();
                billingGet.CustomertNo = billing.CustomertNo;
                billingGet.Date = billing.Date;
                billingGet.Amount = billing.Amount;
                billingGet.IsPaid = billing.IsPaid;
                dbContext.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(billing);
        }

        public ActionResult delete(int Id) 
        {
            using (var dbContext = new AppDbContext())
            {
                dbContext.Database.EnsureCreated();

                Billing billingGet = dbContext.Billings.Where(x => x.BillNo == Id).FirstOrDefault();
                dbContext.Remove(billingGet);
                dbContext.SaveChanges();
                return RedirectToAction("Index");

            }
        }
    }
}

Demo_projects/Controllers/HomeController.cs
using Demo_projects.AppContectDb;
using Demo_projects.Models;
using Microsoft.AspNetCore.Mvc;
using System.Data.SQLite;
using System.Diagnostics;

namespace Demo_projects.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        SQLiteConnection connection = new SQLiteConnection("Data Source=billingNew.db");
        public IActionResult Index()
        {
            var data = Cls.DisplayBillingTable(connection);
            return View(data);
        }


        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Billing billing)
        {

            Cls.InsertBillingRecord(connection, billing);
            return RedirectToAction("Index");


            return View();
        }



        public IActionResult Edit(int Id)
        {
            var data = Cls.EditBillingRecordGetById(connection, Id);

            return View(data);
        }
        [HttpPost]
        public IActionResult Edit(Billing billing)
        {
            Cls.EditBillingRecord(connection, billing);
            return RedirectToAction("Index");
            return View(billing);
        }

        public ActionResult delete(int Id)
        {
            using (var dbContext = new AppDbContext())
            {
                dbContext.Database.EnsureCreated();

                Billing billingGet = dbContext.Billings.Where(x => x.BillNo == Id).FirstOrDefault();
                dbContext.Remove(billingGet);
                dbContext.SaveChanges();
                return RedirectToAction("Index");

            }
        }



        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Demo_projects/Views/Billing/Create.cshtml
@model Demo_projects.Models.Billing

<div class="container">
    <div class="row">
        <div class="col-md-8 offset-2">
            <div class="card">
                <div class="card-header">
                    <h1 class="text-center text-primary">Add Bill</h1>
                </div>
                <div class="card-body">
                    <form method="post" action="Create">
                        <div class="form-group mt-3">
                            @Html.LabelFor(model => Model.CustomertNo, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.CustomertNo, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.CustomertNo, "", new { @class = "text-danger" })
                        </div>                                               
                        <div class="form-group">
                            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Pay Now" style="color: white;" class="btn btn-sm btn-outline-success float-end bg-success" />
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>

Demo_projects/Views/Billing/Edit.cshtml
@model Demo_projects.Models.Billing

<div class="container">
    <div class="row">
        <div class="col-md-8 offset-2">
            <div class="card">
                <div class="card-header">
                    <h1 class="text-center text-primary">Edit Bill</h1>
                </div>
                <div class="card-body">
                    @using (Html.BeginForm("Edit", "Billing", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-group">
                            @Html.LabelFor(model => model.BillNo, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.BillNo, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.BillNo, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.CustomertNo, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.CustomertNo,  new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.CustomertNo, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Update" class="btn btn-primary" />
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

Demo_projects/Views/Billing/Index.cshtml
@model IEnumerable<Demo_projects.Models.Billing>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="text-center text-primary">Billing Record</h1>
            <p class="text-center text-success">@TempData["Error"]</p>
            <a class="btn btn-sm btn-success m-1" asp-controller="Billing" asp-action="Create">Add Bill</a>
             <table class="table table-bordered">
                <tr class="text-center">
                    <th>Biil No</th>
                    <th>Customert No</th>
                    <th>Date</th>
                    <th>Amount</th>
                    <th>IsPaid</th>
                    <th>Action</th>
                </tr>
                @if (Model != null)
                {
                   @foreach (var item in Model)
                   {
                         <tr class="text-center">
                               <td>@item.BillNo</td>
                               <td>@item.CustomertNo</td>
                               <td>@item.Date</td>
                               <td>@item.Amount</td>
                               <td>@item.IsPaid</td>
                            
                               <td>
                                <a class="btn btn-sm btn-warning" asp-controller="Billing" asp-action="Edit" asp-route-Id="@item.BillNo">Edit Bill</a>
                                <a class="btn btn-sm btn-danger" asp-controller="Billing" asp-action="delete" asp-route-Id="@item.BillNo">Delete Bill</a>
                               </td>                     

                         </tr>
                   }
                }                               
             </table>
        </div>
    </div>
</div>

Demo_projects/Views/Home/Create.cshtml
@model Demo_projects.Models.Billing

<div class="container">
    <div class="row">
        <div class="col-md-8 offset-2">
            <div class="card">
                <div class="card-header">
                    <h1 class="text-center text-primary">Add Bill</h1>
                </div>
                <div class="card-body">
                    <form method="post" action="Create">
                        <div class="form-group mt-3">
                            @Html.LabelFor(model => Model.CustomertNo, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.CustomertNo, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.CustomertNo, "", new { @class = "text-danger" })
                        </div>                                               
                        <div class="form-group">
                            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Pay Now" style="color: white;" class="btn btn-sm btn-outline-success float-end bg-success" />
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>

Demo_projects/Views/Home/Edit.cshtml
@model Demo_projects.Models.Billing

<div class="container">
    <div class="row">
        <div class="col-md-8 offset-2">
            <div class="card">
                <div class="card-header">
                    <h1 class="text-center text-primary">Edit Bill</h1>
                </div>
                <div class="card-body">
                    @using (Html.BeginForm("Edit", "Home", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-group">
                            @Html.LabelFor(model => model.BillNo, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.BillNo, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.BillNo, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.CustomertNo, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.CustomertNo,  new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.CustomertNo, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Update" class="btn btn-primary" />
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

Demo_projects/Views/Home/Index.cshtml
@model IEnumerable<Demo_projects.Models.Billing>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="text-center text-primary">Home Record</h1>
            <p class="text-center text-success">@TempData["Error"]</p>
            <a class="btn btn-sm btn-success m-1" asp-controller="Home" asp-action="Create">Add Bill</a>
             <table class="table table-bordered">
                <tr class="text-center">
                    <th>Biil No</th>
                    <th>Customert No</th>
                    <th>Date</th>
                    <th>Amount</th>
                    <th>IsPaid</th>
                    <th>Action</th>
                </tr>
                @if (Model != null)
                {
                   @foreach (var item in Model)
                   {
                         <tr class="text-center">
                               <td>@item.BillNo</td>
                               <td>@item.CustomertNo</td>
                               <td>@item.Date</td>
                               <td>@item.Amount</td>
                               <td>@item.IsPaid</td>
                            
                               <td>
                                <a class="btn btn-sm btn-warning" asp-controller="Home" asp-action="Edit" asp-route-Id="@item.BillNo">Edit Bill</a>
                                <a class="btn btn-sm btn-danger" asp-controller="Home" asp-action="delete" asp-route-Id="@item.BillNo">Delete Bill</a>
                               </td>                     

                         </tr>
                   }
                }                               
             </table>
        </div>
    </div>
</div>

Demo_projects/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Demo_projects</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Demo_projects.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Demo_projects</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Demo_projects - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>